name: Deploy Pre-production

on:
  push:
    branches:
      - pre-production

concurrency:
  group: quickdialog-pre-production
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Pre-production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Pre-production
        run: echo "deploy pre-production"
