name: Deploy Pre-production

on:
  push:
    branches:
      - pre-production

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  deploy:
    name: Deploy Pre-production
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Pre-production
        run: echo "deploy pre-production test for deployment"
